@baseUrl = http://localhost:3333



###

# @name CreateAccount
POST {{baseUrl}}/users/register
Content-Type: application/json

{
    "user": "fazendateste@teste",
    "password": "123123",
    "fazendaId": "e3a58212-de11-4142-945c-e0d8384efa3e"
}


###

# @name CreateFarm
POST {{baseUrl}}/fazenda/register
Content-Type: application/json

{
    "nome": "Fazenda Teste"
}


###

# @name Login
POST {{baseUrl}}/users/authenticate
Content-Type: application/json

{
    "user": "fazendateste@teste",
    "password": "123123"
}


### 
# @name GetApontamentos
GET {{baseUrl}}/apontamentos/recentes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmYXplbmRhX2lkIjoiZTNhNTgyMTItZGUxMS00MTQyLTk0NWMtZTBkODM4NGVmYTNlIiwiZmF6ZW5kYU5vbWUiOiJGYXplbmRhIE5pY29sZSIsInN1YiI6ImM3ZWNlMDRmLTBlYzItNDFkNS04ZTdiLTcxN2Y4N2I4YTQ3NCIsImlhdCI6MTc1NjI2ODY4Mn0.yX6ARbo-R_GeJ5eSuAqWsQzgVt7kXDdCIRCVH-3mKQI


### 
# @name GetApontamentosExtra
GET {{baseUrl}}/apontamentos/extras?dataInicio=2024-01-01&dataFim=2025-10-11
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmYXplbmRhX2lkIjoiZTNhNTgyMTItZGUxMS00MTQyLTk0NWMtZTBkODM4NGVmYTNlIiwiZmF6ZW5kYU5vbWUiOiJGYXplbmRhIE5pY29sZSIsInN1YiI6ImM3ZWNlMDRmLTBlYzItNDFkNS04ZTdiLTcxN2Y4N2I4YTQ3NCIsImlhdCI6MTc1NjI2ODY4Mn0.yX6ARbo-R_GeJ5eSuAqWsQzgVt7kXDdCIRCVH-3mKQI