@baseUrl = http://localhost:3333



###

# @name CreateAccount
POST {{baseUrl}}/users/register
Content-Type: application/json

{
    "user": "fazendateste@teste",
    "password": "123123",
    "fazendaId": "e3a58212-de11-4142-945c-e0d8384efa3e"
}


###

# @name CreateFarm
POST {{baseUrl}}/fazenda/register
Content-Type: application/json

{
    "nome": "Fazenda Teste"
}
